services:
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr-test
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        ports:
            - 8989:8989
        volumes:
            - ./testdata/sonarr:/config
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr-test
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        ports:
            - 7878:7878
        volumes:
            - ./testdata/radarr:/config
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent-test
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - WEBUI_PORT=8080
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        volumes:
            - ./testdata/qbittorrent:/config
        restart: unless-stopped

    reducarr:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: reducarr
        image: reducarr:latest
        restart: unless-stopped
        user: "1000:1000"
        ports:
            - "8080:8080"
        environment:
            - REDUCARR_UI_USER=admin
            - REDUCARR_UI_PASS= # Keep empty to generate a password on first launch
            - VERBOSE=1
            - TZ=Europe/Paris
